### ISSUE TITLE
[Q] Clarify how EMA plugin works?

### ISSUE THREAD

**Issue by vedantroy** [mosaicml/composer#1366]
I have a few questions about the EMA docs: https://docs.mosaicml.com/en/latest/method_cards/ema.html
- Will the EMA version of the model automatically be used during inference time?
- What if I want to use the non-EMA version of the model at inference time / perform comparisons between the EMA'd version and the non-EMA'd version on some validation/test set.

**Comment by vedantroy** [comment]
Also, it seems like normally EMA is set with a rate (e.g EMA rate = 0.999). Is there a way to set the EMA rate like that? It would make it easier to replicate papers, like this: https://arxiv.org/pdf/2102.09672.pdf

**Comment by hanlint** [comment]
cc: @coryMosaicML to help answer these questions!

**Comment by vedantroy** [comment]
@coryMosaicML, any update on this?

**Comment by coryMosaicML** [comment]
Hi there, apologies for missing this earlier...

> * Will the EMA version of the model automatically be used during inference time?

It does depend a bit on how you export the model for inference, but likely this will not happen automatically. If you want to be sure you're extracting the EMA weights, you can do it explicitly from the EMA algorithm object via `ema_model = ema.get_ema_model(model)` where `model` is the model object you want to load the EMA weights onto. It's quite clunky at the moment; it's on my todo list to make this happen automatically.

> * What if I want to use the non-EMA version of the model at inference time / perform comparisons between the EMA'd version and the non-EMA'd version on some validation/test set.

By default, this should be what is stored in Composer's `state.model`, and this is what you'll get at the end of training, so using this model without the step above should give you the non-EMA version of the model. 

> Also, it seems like normally EMA is set with a rate (e.g EMA rate = 0.999). Is there a way to set the EMA rate like that? It would make it easier to replicate papers, like this: https://arxiv.org/pdf/2102.09672.pdf

Yes, you can convert between `half_life` and this more familiar parameter (which we called `smoothing` in Composer's functional implementation of EMA) via `half_life = -update_interval * log(2) / log(smoothing)`, so for a value of `smoothing=0.999` and `update_interval = "1ba"` you should set `half_life ="693ba"`. Note that this does currently have the restriction that `half_life` must be an integer number of batches. We used `half_life` rather than `smoothing` to set the EMA rate for interpretability and to allow one to change `update_interval` without having to change the EMA rate to compensate.

**Comment by hanlint** [comment]
Closing as stale -- @vedantroy please re-open if more questions!
