### ISSUE TITLE
Rename `SomethingHparams` to `SomethingConfig` where appropriate

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#280]
We often use variables names such as `deepspeed_hparams`, or `object_store_hparams`, when they should properly be called `config` as they are not usually considered hyperparameters. For example, deepspeed documentation refers to `deepspeed_config`. As part of deYAHPification, we should standardize our nomenclature around `config` instead of `hparams` for many more systems-level objects.

**Comment by ravi-mosaicml** [comment]
After AutoYAHP, and excluding all model, optimizer, and dataset hparam classes (since those really are hparams), the only classes left are the ObjectStoreLoggerHparams, TrainerHparams, FitHparams, EvalHparams, ExperimentHparams, LibcloudObjectStoreHparams, and DataLoaderHparams. I think it would introduce confusion to call these “config” when yahp and our models / datasets refer to the similar structures as hparams (in addition to causing a breaking change for no added functionality). As such, would prefer to leave as-is and keep calling this as SomethingHparams.
