### ISSUE TITLE
Scheduler hparams interval default value should be 'step' instead of 'epoch'

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#287]
## 🚀 Feature Request
All of the [`SchedulerHparams` classes](https://github.com/mosaicml/composer/blob/main/composer/optim/scheduler.py) have `epoch` as the default value for `interval`. The default value seems like it should be `step`, because stepwise LR updates yield superior performance.

**Comment by growlix** [comment]
Soliciting @hanlint, @abhi-mosaic, @ravi-mosaicml for thoughts

**Comment by ravi-mosaicml** [comment]
Is the the pytorch convention where schedulers step every batch or epoch? I
think we should match it.

**Comment by abhi-mosaic** [comment]
@ravi-mosaicml The Pytorch schedulers are pretty bad, I would prefer not to follow convention for convention's sake. I think step-wise as default makes sense as a best practice, and we've documented it in blog posts. And since we are handling the `.step()` calls within Trainer it won't impose anything on the user.

**Comment by hanlint** [comment]
We originally set it to to default to `epoch`, since that's the pytorch default. However, I am OK with what is suggested here given our blog posts / best practices.
