### ISSUE TITLE
Update algorithm metadata

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#447]
In each algorithm's `__init__.py` file, there is a metadata block along the lines of:
```
_name = 'SqueezeExcite'
_class_name = 'SqueezeExcite'
_functional = 'apply_se'
_tldr = 'Replaces eligible layers with Squeeze-Excite layers'
_attribution = 'Hu et al, 2017'
_link = 'https://arxiv.org/abs/1709.01507'
_method_card = ''
```

Because of #446 along with API changes like #426 , these metadata fields are often out of date. Also, it appears that many of them:

1. never got links to the method cards in the first place, or
2. have only a subset of their functional API listed.

And, because of #446, factorization has no metadata at all.

**Comment by ravi-mosaicml** [comment]
Instead of putting this in `__init__`.py, thoughts about putting it as class-level attributes on each Algorithm? For example

```python3
class SqueezeExcite(Algorithm):
    """Replaces eligible layers with Squeeze-Excite layers
    
    exxtended docstring"""
    name = "My Algorithm"
    attribution = "Hu et al, 2017"
    link = "https://arxiv.org/abs/1709.01507"
    functional = apply_se

```

If we went with this approach, then we wouldn't need the classname or tldr fields anymore (the tldr should be the first line of the docstring).

We need to update and embed the tables in the sphinx doc build (see #448), so I'll wait for resolution on this issue before working on that.

**Comment by hanlint** [comment]
Completed via #471 and metadata updated.
