### ISSUE TITLE
Centralize NLP tokenizers (and potentially model configs)

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#481]
# Problem
Two parts of the NLP stack need access to the tokenizer and model configuration. More specifically, the models (in order to know which inputs are required for the forward pass) and Datasets (in order to tokenize the dataset input)

https://github.com/mosaicml/composer/blob/ab0da9ee5a4fcb72ad9461581cac99c8410dac3b/composer/models/transformer_shared.py#L43
https://github.com/mosaicml/composer/blob/ab0da9ee5a4fcb72ad9461581cac99c8410dac3b/composer/models/transformer_shared.py#L42
https://github.com/mosaicml/composer/blob/ab0da9ee5a4fcb72ad9461581cac99c8410dac3b/composer/datasets/lm_datasets.py#L85
https://github.com/mosaicml/composer/blob/ab0da9ee5a4fcb72ad9461581cac99c8410dac3b/composer/datasets/lm_datasets.py#L86

This leads to some messy user experiences, such as specifying the tokenizer three times in the YAML:
https://github.com/mosaicml/composer/blob/cf33785f95407dc19eafd118c9cd14d7a2b47295/composer/yamls/models/glue/qnli.yaml#L4
https://github.com/mosaicml/composer/blob/cf33785f95407dc19eafd118c9cd14d7a2b47295/composer/yamls/models/glue/qnli.yaml#L12
https://github.com/mosaicml/composer/blob/cf33785f95407dc19eafd118c9cd14d7a2b47295/composer/yamls/models/glue/qnli.yaml#L21

I think it might be better design if we can centralize the storage of these in a single place, which would be cleaner design and lead to less room for error. However, there is the question of "where would we store it?"

Open to opinions!

**Comment by ravi-mosaicml** [comment]
I believe this problem is limited to the YAHP route, as the user would pass an already-constructed model and dataloader into Composer. We ran into a similar issue in image classification, where the model (and sometime algorithms) needed to know the number of classes from the dataset.

One idea is to pass the initialized model when constructing the datasets (e.g. `train_dataset = train_dataset_hparams.initailize_object(batch_size, dataloader_hparams, model)`). The tokenizer could be a model attribute, and the `DatasetHparams` would know to read that attribute. We already do something similar for image classification, where `num_classes` is an attribute of `ComposerClassifier`. We would just need to update the YAHP code-path to pass the already-constructed model when initializing the dataloaders.

Thoughts?

@moinnadeem going to assign to you to design and implement. The above proposal, if it would solve this problem, should be fairly straightforward to do in `trainer_hparams.py`.
