### ISSUE TITLE
RunDirectoryUploader should take an ObjectStoreProvider, not an ObjectStoreProviderHparams

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#523]
Improper mixing of `hparams` objects with the normal codepath.

**Comment by ravi-mosaicml** [comment]
This one is going to be trickiest to solve, as the run directory uploader needs a builder for the object store provider. The hparams is the simplest way to get that.

A simple solution would be to take a callable that returns an ObjectStoreProvider, which `ObjectStoreProviderHparams.initialize_object` would satisfy, but then the user would be responsible for writing their own lambda rather than using a class that already does this functionality.
