### ISSUE TITLE
Handle synthetic versions of models in a more centralized manner

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#559]
# 🚀 Feature Request
When creating unit tests, we need to modify models to handle unit test requirements (such as not downloading pretrained weights, making the model smaller for testing purposes, etc). We currently handle this in the testing code (example: https://github.com/mosaicml/composer/blob/dev/tests/test_hparams.py#L63-L65). 

In contrast, for datasets, we have a `use_synthetic` flag that can be used to override properties of the dataset via a SyntheticHparamsMixin.
https://github.com/mosaicml/composer/blob/dev/composer/datasets/hparams.py#L27

https://github.com/mosaicml/composer/blob/dev/composer/datasets/imagenet.py#L38-L50

How should we go about doing something similar for models?

I'm interested in a few properties:
1) Size down the model in order to be quickly instantiated and have a reasonable forward pass on the CPU.
2) Modify the hparams to randomly initialize model weights instead of downloading pretrained model
3) Generate a synthetic tokenizer to avoid downloading the tokenizer from the internet.

Design discussion topics:
1) Do we want the model to handle `use_synthetic`, or should a method in the test suite handle modifying models?

**Comment by hanlint** [comment]
For unittests, the current preferred pattern is to _not_ use `use_synthetic` datasets wherever possible in favor of maintaining minimal standalone reference datasets and models (see `tests/common.py`). This is motivated by:
1. keeping the testing code simple and easy to understand/debug. Also easier for users to read the unittests and understand how the function works.
2. The reference models/datasets enforces an external facing API for our code, as opposed to using internal datasets/loaders that may be changing. 

The `use_synthetic` codepath for datasets is tolerated because it can be useful for the user.

I'd recommend we not add a `use_synthetic` to our models since that's adding extra code to every model purely for the purposes of supporting testing. Instead, add a minimal NLP model `class ToyTransformer(ComposerTransformer)` to `test/common.py` for unittest algorithms, and to test the real models, use patching and mocks to achieve the goal. 

For example, to test the `BERT` model, we can mock a synthetic tokenizer by doing something like the following:
```
from unittest.mock import patch

with patch("transformers.AutoTokenizer.from_pretrained") as mock_tokenizer:
    mock_tokenizer.return_value = # insert synthetic tokenizer here

    bert = BERT(...)
```

Would something like this work?

**Comment by moinnadeem** [comment]
Ah, I see -- let me try and implement this and see if I have any questions!

**Comment by ravi-mosaicml** [comment]
Closing this issue for #691 and #117. We will disable network access in tests later on, which will force us to use random initialization for models.
