### ISSUE TITLE
Pin the pyright version

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#593]
The environment variable `PYRIGHT_PYTHON_FORCE_VERSION` needs to be set when pyright is installed from pip. Ideally we can set this variable in the setup.py (e.g. `os.environ['PYRIGHT_PYTHON_FORCE_VERSION'] = '...'`); but if not, then it should be in the `.ci/Jenkinsfile`.

**Comment by bandish-shah** [comment]
Tried setting `PYRIGHT_PYTHON_FORCE_VERSION` in `setup.py`, unfortunately this does not persist.

The next best place is the Makefile since it will propagate to CI and manual user runs (if using the Makefile targets).  

It's a minor inconvenience if users just wish to do `pyright .` but we can split the `lint` Makefile target into `lint-style` and `lint-pyright` if users wish to invoke just the linter.  Using the Makefile has the added benefit of being the same workflow as CI so we should already be urging users to be running the lint checks via make targets vs invoking the utilities directly.

**Comment by ravi-mosaicml** [comment]
Fixed in #612
