### ISSUE TITLE
Dark Mode on ReadTheDocs should automatically activate based on OS preferences

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#754]
The ReadTheDocs page goes into dark mode based off of a button, but it should follow OS preferences when available.

**Comment by hanlint** [comment]
I was unable to reproduce this issue -- I switched my macOS settings, and when creating an incognito window, `docs.mosaicml.com` loaded either dark or light.

Unlike github.com however, your the mode does persist when you change in the settings. Since this is an edge case (e.g. switching from light -> dark while having the page open), going to close this issue.
