### ISSUE TITLE
Improved `wandb` logging experience

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#826]
Based on feedback from @tcapelle, our `wandb` logging experience can be improved with better naming, and more default things logged, see comment here:

> We could improve the naming of the wandb logging variables (we get a bunch of panes with weird names).
I will wait your next release to take a look. Also you are not logging anything to the config, you can pull a bunch of data from the Trainer and the ComposerModel. Look at all that fastai get's you for free: batch_size, epochs, loss_func, metrics_names, callbacks, loggers, flags, etc...

From: https://github.com/mosaicml/composer/issues/809#issuecomment-1079026212

**Comment by abhi-mosaic** [comment]
Adding an additional request here, we should change our WandB checkpoint logging to use the `wandb.save()` rather than `wandb.log_artifact()`. The former is run-specific and is the simplest way to log files and checkpoints. The latter is for model versioning and keeping track of "latest" or "best" model checkpoints across many runs. For this reason WandB Artifacts are aggregated across a whole project, which is probably not what people want to do by default.
