### ISSUE TITLE
`resize_size` on `val_dataset` changes `wall_clock_train`

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#984]
** Environment **

- image: `pytorch_internal`
- branch: `dev`
- Hardware (GPU, or instance type): r1z1 8x A100

** To reproduce

1. Run `composer -n 8 examples/run_composer_trainer.py -f composer/yamls/models/resnet50.yaml --val_dataset.imagenet.resize_size 232` (will need to provide your own dataset path/hparams)
2. Run `composer -n 8 examples/run_composer_trainer.py -f composer/yamls/models/resnet50.yaml`
3. Compare `wall_clock_time` for each run

## Expected behavior

`wall_clock_train` should be unaffected by changes to validation. Instead, setting `resize_size` (in this case to `232`) increases `wall_clock_train` by about 8%. [See W&B runs](https://wandb.ai/mosaic-ml/resnet-high-score/reports/Composer-ResNet50--VmlldzoxODc4NTMx#-validation-resizing-slows-wall_clock_train).

**Comment by ravi-mosaicml** [comment]
Thanks @growlix, good catch.

The underlying issue is that the [Speed Monitor](https://github.com/mosaicml/composer/blob/0e4955e6e60d96cc37680b99a77c16966d342803/composer/callbacks/speed_monitor.py#L17) does not stop time tracking during evaluation.

We can stop time tracking between `Event.EVAL_START` and `Event.EVAL_END`. However, would it sense to track the total wall clock time separately from the train-only wall clock time?
